# ========================
# SERVER
# ========================
server.port=8084
spring.application.name=admin-service

# ========================
# DATABASE (use separate DB or same DB with different schema)
# ========================
spring.datasource.url=jdbc:mysql://localhost:3306/admin_db
spring.datasource.username=root
spring.datasource.password=Varshith@100
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# ========================
# EUREKA
# ========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ========================
# SWAGGER
# ========================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
