server.port=8080
spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=catalog-service
spring.cloud.gateway.routes[0].uri=lb://CATALOG-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/catalog/**
