# ========================
# SERVER
# ========================
server.port=8080
spring.application.name=api-gateway

# ========================
# CORS
# ========================
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

# ========================
# ROUTES
# ========================

# AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/auth/(?<segment>.*), /${segment}

# CATALOG SERVICE
spring.cloud.gateway.routes[1].id=catalog-service
spring.cloud.gateway.routes[1].uri=lb://CATALOG-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/catalog/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/catalog/(?<segment>.*), /${segment}

# ORDER SERVICE
spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/orders/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/orders/(?<segment>.*), /${segment}

# ========================
# SWAGGER ROUTES
# ========================

spring.cloud.gateway.routes[3].id=auth-swagger
spring.cloud.gateway.routes[3].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth/v3/api-docs

spring.cloud.gateway.routes[4].id=catalog-swagger
spring.cloud.gateway.routes[4].uri=lb://CATALOG-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/catalog/v3/api-docs

spring.cloud.gateway.routes[5].id=order-swagger
spring.cloud.gateway.routes[5].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/orders/v3/api-docs

# ========================
# SWAGGER UI AGGREGATION
# ========================
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=Catalog Service
springdoc.swagger-ui.urls[1].url=/catalog/v3/api-docs

springdoc.swagger-ui.urls[2].name=Order Service
springdoc.swagger-ui.urls[2].url=/orders/v3/api-docs
